### DISCUSSION TITLE
The helm chart needs a new release, the current release is broken.

### DISCUSSION THREAD

**Discussion by tomalexander** [tektoncd/operator#2098] [General]
The most recent tag is `tekton-operator-0.70.0`. This does not include the stepaction permissions that were added in `f736eb00fc17b25de72f704e63bc41811cfcf2e4`. Installing the helm chart from that tag and then creating this TektonConfig:

```
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
  namespace: tekton-operator
spec:
  profile: all
  targetNamespace: tekton-pipelines
  pruner:
    resources:
      - pipelinerun
      - taskrun
    keep: ~
    keep-since: 86400
    schedule: "0,30 * * * *"
  pipeline:
    running-in-environment-with-injected-sidecars: false
    disable-affinity-assistant: true
    embedded-status: "minimal"
    enable-api-fields: "beta"
  dashboard:
    readonly: true
```

results in the `pipeline-main-static-*` tektoninstallerset having this error:
```
    Message:               Install failed with message: clusterroles.rbac.authorization.k8s.io "tekton-pipelines-controller-cluster-access" is forbidden: user "system:serviceaccount:tekton-operator:tekton-operator" (groups=["system:serviceaccounts" "system:serviceaccounts:tekton-operator" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:["tekton.dev"], Resources:["stepactions"], Verbs:["get" "list" "create" "update" "delete" "patch" "watch"]}
{APIGroups:["tekton.dev"], Resources:["stepactions/status"], Verbs:["get" "list" "create" "update" "delete" "patch" "watch"]}
```
