### DISCUSSION TITLE
Excluding labels from resources

### DISCUSSION THREAD

**Discussion by aivanov-citc** [tektoncd/operator#354] [Q&A]
Good day!
We use the "flux" gitops system for deployment in kubernetes. With this deployment, flux enriches all its monitored resources with kustomize.toolkit.fluxcd.io labels.
```yaml
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/checksum: 26e76783fe67394af7962245bee382b6bc44087c
    kustomize.toolkit.fluxcd.io/name: workloads-sync
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: kogito-wrapper
  namespace: default
spec:
  ...

kind: Deployment
apiVersion: apps/v1
metadata:
  name: el-kogito-wrap-event-listener
  namespace: default
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: kogito-wrap-event-listener
    kustomize.toolkit.fluxcd.io/checksum: 26e76783fe67394af7962245bee382b6bc44087c
    kustomize.toolkit.fluxcd.io/name: workloads-sync
    kustomize.toolkit.fluxcd.io/namespace: flux-system
```
If it is possible to remove the inheritance of some labels from resources when processed by the operator? Remove by mask flux labels
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: el-kogito-wrap-event-listener
  namespace: default
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: kogito-wrap-event-listener
```
