### DISCUSSION TITLE
How to bind secrets to 'pipeline' service account shipped by pipeline operator

### DISCUSSION THREAD

**Discussion by bilalbokharee** [tektoncd/operator#629] [Q&A]
I am trying to extend the service account "pipeline", managed by tektonConfig, by adding authentication secrets for docker that are consumed by pipeline tasks. Is it possible to achieve this?

```
kind: ServiceAccount
apiVersion: v1
metadata:
  name: pipeline
  namespace: <my-namespace>
secrets:
  - name: pipeline-token-47qcr
  - name: pipeline-dockercfg-vrt2h
imagePullSecrets:
  - name: pipeline-dockercfg-vrt2h
``` 
Here, under `secrets:` I want to add a couple more secrets. Is this achievable?
