### ISSUE TITLE
Cannot set the embedded-status feature flag on TektonConfig

### ISSUE THREAD

**Issue by gsouzab** [tektoncd/operator#1021]
# Expected Behavior

While testing the **matrix** feature, I tried to configure the feature flag `embedded-status` using the `TektonConfig` custom resource.  Like the other feature flags, I expected this one to be configurable the same way, but apparently, it is not a valid [property](https://tekton.dev/docs/operator/tektonpipeline/#properties).

# Actual Behavior

I receive the following error:

`BadRequest, error: admission webhook "webhook.operator.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "embedded-status"`

# Steps to Reproduce the Problem

1. Create a Tekton config CR with the embedded-status property
```
  apiVersion: operator.tekton.dev/v1alpha1
  kind: TektonConfig
  metadata:
    name: config
  spec:
    targetNamespace: tekton-pipelines
    profile: all
    pipeline:
      embedded-status: minimal
      enable-api-fields: alpha
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.10-eks-84b4fe6", GitCommit:"cc6a1b4915a99f49f5510ef0667f94b9ca832a8a", GitTreeState:"clean", BuildDate:"2022-06-09T18:24:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
`v0.39.0`

- Operator version:
`v0.61.0`
