### ISSUE TITLE
Need ability to set resource requests and limits for Tekton components 

### ISSUE THREAD

**Issue by tonygilkerson** [tektoncd/operator#1037]
### Feature request

I would like to set the container `resources` for the components created by the Tekton-Operator, i.e. tekton-dashboard and tekton-pipelines-controller deployments. It would be nice to enable this in the TektonConfig as shown below in the yaml snipit.

```yaml
kind: TektonConfig
metadata:
  name: config
spec:
  ...
  dashboard:
    resources: ...
    ...
  pipeline:
    resources: ...
    ...
  targetNamespace: tekton-pipelines
  trigger:
    resources: ....
```

I also need to set the resources for the `tekton-operator-proxy-webhook` and `tekton-triggers-webhook` but I am not sure where that should be specified. 

### Use case

The team I am on have a goal to set the request and limits for every workload. We even have rules that look at the ratio of requests to limit and if they are too far apart the pod will not get scheduled. This is in an effort to make are k8s scheduler efficient and make the entire cluster stable even when under a heavy load.

**Comment by piyush-garg** [comment]
@tonygilkerson Thanks for this.

The feature requests seems reasonable, we need to design the api a bit. Do we need something specific for each component or a generic for all component will also work.

**Comment by jkandasa** [comment]
@tonygilkerson Now it is possible to add resource limits via `options` field. This feature is available from v0.68.0: #1656

Example:
```yaml
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  chain:
    options:
      deployments:
        tekton-chains-controller:
          spec:
            template:
              spec:
                containers:
                  - name: tekton-chains-controller
                    resources:
                      requests:
                        memory: "128Mi"
                        cpu: "200m"
                      limits:
                        memory: "512Mi"
                        cpu: "1"
  pipeline:
    options:
      deployments:
        tekton-pipelines-controller:
          spec:
            template:
              spec:
                containers: 
                  - name: tekton-pipelines-controller
                    resources:
                      requests:
                        memory: "512Mi"
                        cpu: "500m"
                      limits:
                        memory: "2Gi"
                        cpu: "2"
```

Kindly reopen the issue, if you feel something not addressed. Thanks!
