### ISSUE TITLE
Pruner doesn't work as expected: "Error: unrecognized type: string"

### ISSUE THREAD

**Issue by wilstdu** [tektoncd/operator#1292]
# Expected Behavior

Pruner deletes PipelineRuns and leaves X latest PipelineRuns per namespace

# Actual Behavior

tekton-resource-pruner CronJob throws error "Error: unrecognized type: string" while pruning certain namespaces. 

# Steps to Reproduce the Problem
- Somewhat unpredictable

# Additional Info
Total number of PipelineRuns in the Cluster: ~ 3.4k
Total number of namespaces: 147
One namespace has majority of PipelineRuns ~3k

> ***NOTE***: namespace names have been replaced. Namespace format is ci-sha256.

Shortened output of tekton-resource-pruner job log:
```
All but 500 PipelineRuns(Completed) deleted in namespace "ci-1"
Error: unrecognized type: string
All but 500 PipelineRuns(Completed) deleted in namespace "ci-3"
```

Namespace with highest number of PipelineRuns was not in the log, so I assume it fell under one of the error records (8/147).
Tried to prune namespace with ~3k PipelineRuns using tkn cli:
```tkn pipelinerun delete --keep 500 -n ci-2``` - it went through flawlessly.

- Kubernetes version:
  ```
  Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.14-eks-ffeb93d", GitCommit:"96e7d52c98a32f2b296ca7f19dc9346cf79915ba", GitTreeState:"clean", BuildDate:"2022-11-29T18:43:31Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:
  ```
  Client version: 0.29.0
  Pipeline version: v0.40.0
  Triggers version: v0.21.0
  Dashboard version: v0.30.0
  Operator version: v0.62.0
  ```

```yaml
# NOTE: some irrelevant values have been removed and list of namespaces has been trimmed
apiVersion: batch/v1
kind: CronJob
metadata:
  name: tekton-resource-pruner-9zthx
  namespace: tekton-pipelines
  labels:
    tektonconfig.operator.tekton.dev/pruner: 'true'
  annotations:
    operator.tekton.dev/last-applied-hash: ccd95aec9374355a89cdfd7ee0d43bffbdc4d34e28bd8ec0e2301e04b1cc5f69
  ownerReferences:
    - apiVersion: operator.tekton.dev/v1alpha1
      kind: TektonConfig
      name: config
      controller: true
      blockOwnerDeletion: true
    - manager: kube-controller-manager
      operation: Update
      apiVersion: batch/v1
      fieldsType: FieldsV1
      subresource: status
  selfLink: >-
    /apis/batch/v1/namespaces/tekton-pipelines/cronjobs/tekton-resource-pruner-9zthx
spec:
  schedule: 0 6 * * *
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
            - name: pruner-tkn-tekton-pipelines-vrfbn
              image: >-
                gcr.io/tekton-releases/dogfooding/tkn@sha256:025de221fb059ca24a3b2d988889ea34bce48dc76c0cf0d6b4499edb8c21325f
              command:
                - /bin/sh
                - '-c'
                - >-
                  function prune() { n=$1; a=$2; resources=$3; old_ifs=" ";
                  IFS=","; for r in $resources; do tkn $r delete -n=$n $a -f;
                  done; IFS=$old_ifs; }; echo $conf; for c in $*; do ns=$(echo
                  $c | cut -d ";" -f 1); args=$(echo $c | cut -d ";" -f 2);
                  resources=$(echo $c | cut -d ";" -f 3); prune $ns $args
                  $resources; done;
              args:
                - '-s'
                - ' ci-1;--keep=500;pipelinerun ci-2;--keep=500;pipelinerun ci-3;--keep=500;pipelinerun'
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: FallbackToLogsOnError
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          nodeSelector:
            kubernetes.io/os: linux
          serviceAccountName: tekton-pipelines-controller
          serviceAccount: tekton-pipelines-controller
          schedulerName: default-scheduler
      ttlSecondsAfterFinished: 3600
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

```
