### ISSUE TITLE
TektonPipeline Resource status.conditions always appended

### ISSUE THREAD

**Issue by bkmeneguello** [tektoncd/operator#133]
# Expected Behavior

I expect only relevant conditions to be appended to the list

# Actual Behavior

There are multiple copies of the same status appended:

```yaml
...
status:
  conditions:
  - code: installed
    version: v0.15.1
  - code: installing
    version: v0.15.1
  - code: installed
    version: v0.15.1
  - code: installing
    version: v0.15.1
  - code: installed
    version: v0.15.1
  - code: installing
    version: v0.15.1
  - code: installed
    version: v0.15.1
  - code: installing
    version: v0.15.1
  - code: installed
    version: v0.15.1
  - code: installing
    version: v0.15.1
  - code: installed
    version: v0.15.1
  - code: installing
    version: v0.15.1
  - code: installed
    version: v0.15.1
  - code: installing
    version: v0.15.1
  - code: installed
    version: v0.15.1
  - code: installing
    version: v0.15.1
```

# Steps to Reproduce the Problem

1. Just install the operator
2. Check the resource

# Additional Info

There is no check before append at [pipeline_controller.go#L325](https://github.com/tektoncd/operator/blob/cf1f2174a092cc3d76a42ecead30ef600b553d1e/pkg/controller/pipeline/pipeline_controller.go#L325)
