### ISSUE TITLE
When creating the TektonInstallerSet  from TektonHub CR, not updating the catalogRefreshInterval

### ISSUE THREAD

**Issue by manojbison** [tektoncd/operator#1347]
# Expected Behavior

- Update the catalogRefreshInterval field in the tektonhub Custom Resource Definition to 10 minutes. This update should automatically create the tekton-hub-api ConfigMap with the same configuration.

# Actual Behavior

- CatalogRefreshInterval in tekton-hub-api configmap shows the default value of 30m instead of 10m

# Steps to Reproduce the Problem

Deploy below CRD 
```
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonHub
metadata:
  name: hub
spec:
  targetNamespace: openshift-pipelines
  api:
    catalogRefreshInterval: 10m
```
and check tekton-hub-api configmap in tekton-pipelines namespace

# Additional Info

- Tekton Pipeline version:
 
1.9.1-4.12
