### ISSUE TITLE
Seemingly incorrect labels in the 0.65 operator release

### ISSUE THREAD

**Issue by brovoca** [tektoncd/operator#1376]
It seems that the labels in line 1009 and 1010 are not correct.

Before:
```yaml
metadata:
  labels:
    app: tekton-operator
    name: tekton-operator-webhook
    operator.tekton.dev/release: v0.64.0
    version: v0.64.0
```

Now:
```yaml
metadata:
  labels:
    app: tekton-operator
    name: tekton-operator-webhook
    operator.tekton.dev/release: devel
    version: devel
```

There are more mentions of "devel" in places where 0.64.0 has been mentioned before.
