### ISSUE TITLE
config-default configmap will be overwritten after some time with default values

### ISSUE THREAD

**Issue by Aldiuser** [tektoncd/operator#1419]
Hello all,

I have installed Tekton Pipelines Operator 1.6.4 on my OpenShift cluster. I have now tried to adjust the `config-defaults` in the openshift-pipelines namespace according to the documentation (see [here](https://tekton.dev/docs/pipelines/additional-configs/#customizing-basic-execution-parameters)). 

This is my snippet: 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-defaults
  namespace: openshift-pipelines
data:
  default-pod-template: |
    nodeSelector:
      node-role.kubernetes.io/infra: ''
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
  default-service-account: pipeline
```

However, I have the problem that after a certain time (at the latest after one day), this ConfigMap is overwritten again. And this with the default values. How can I prevent that my customizations are overwritten again? Do I have to set a flag somewhere, or is something missing in my ConfigMap?

Thanks in advance!

**Comment by Aldiuser** [comment]
How can I change the pod template in TektonConfig? I see a .config section there, but this section only controls the deployments that are deployed by Tekton Operator itself (see [here](https://github.com/tektoncd/operator/blob/main/docs/TektonConfig.md#config)), but not my pods that are created by a PipelineRun. 

Can you maybe write me a sample config?

**Comment by vdemeester** [comment]
@Aldiuser This is [here](https://github.com/tektoncd/operator/blob/main/docs/TektonConfig.md#pipeline) there is a `default-pod-template`. So something like the following would work, I think.

```
  apiVersion: operator.tekton.dev/v1alpha1
  kind: TektonConfig
  metadata:
    name: config
  spec:
    targetNamespace: tekton-pipelines
    profile: all
    config:
      nodeSelector: <>
      tolerations: []
      priorityClassName: system-cluster-critical
    pipeline:
      default-pod-template: |
        nodeSelector:
        # […]
```
