### ISSUE TITLE
config-registry-cert config map is erased when tekton operator pod restarts

### ISSUE THREAD

**Issue by lucienbanholzer** [tektoncd/operator#1429]
Dear team,

In order to be able to pull images from our private registry I need to declare custom SSL certificates in configmap **config-registry-cert**.

The issue is when tekton-operator pod restarts this configmap resource is deleted.

I don't find any solution in tekton operator config to make it persistent.

Do you have a solution for this ?

Thanks a lot for your help,

BR

**Comment by lucienbanholzer** [comment]
Any idea ?

**Comment by vdemeester** [comment]
cc @jkandasa 

This is "expected" behavior so far, as those configmap are managed by the operator. We probably need to add an option to configure this configmap from the operator 👼🏼

**Comment by jkandasa** [comment]
I just checked the code and sadly we do not have an option to ignore it in the current design :slightly_frowning_face: 
On operator pod restarts `installersets` reconciles and revert back the resources into it is original state.

**Comment by jkandasa** [comment]
@lucienbanholzer Now it is possible with additional fields option: https://tekton.dev/vault/operator-main/tektonconfig/#additional-fields-as-options available from `v0.68.0` release.

example:
```yaml
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  pipeline:
    options:
      disabled: false
      configMaps:
        config-registry-cert:
          data:
            # your data
```

Can you please let me know, if something not clear?
