### ISSUE TITLE
[OpenShift] disabling addon takes longer time

### ISSUE THREAD

**Issue by jkandasa** [tektoncd/operator#1440]
version 1.10.0 (v0.65.x)

# Expected Behavior
disabling addon should complete the action in a reasonable time

# Actual Behavior
but takes longer time: approx 20 minutes

# Steps to Reproduce the Problem
Update TektonConfig cr addon vlaues as follows and watch the addon status and reconcile status
```
spec:
  addon:
    params:
      - name: clusterTasks
        value: false 
      - name: pipelineTemplates
        value: false
      - name: communityClusterTasks
        value: false
```
