### ISSUE TITLE
Manage clustertasks from tektoncd/catalog

### ISSUE THREAD

**Issue by ibotty** [tektoncd/operator#160]
# Expected Behavior

ClusterTasks get installed and updated by the operator.

# Actual Behavior

They have to be added/modified manually.

**Comment by vdemeester** [comment]
@ibotty To make sure I understood the request, the idea would be to ship some tasks from the catalog with the operator, and as `ClusterTask` right ? (a similar behavior that OpenShift Pipelines does).

If that's the case then, few questions
- Which one do we ship ?
- How do we decide which one do we ship ?

**Comment by ibotty** [comment]
Yes.  That was the idea.  I assume that one could ship them all, maybe configurably with either white- or blacklist.

```yaml
spec: 
  disableAllDefaultTasks: true
  sources:
  - disabled: false
    name: git-clone
```
or
```yaml
spec:
  disableAllDefaultTasks: false
  sources:
  - disabled: true
    name: aws
```
