### ISSUE TITLE
pipelineruns and taskruns pods are getting pruned regardless of pruner configuration (keep-since)

### ISSUE THREAD

**Issue by cmorinupgrade** [tektoncd/operator#1668]
I am on Tekton Operator v0.67

## TektonConfig manifest

```
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  targetNamespace: tekton-pipelines
  profile: all
  config:
    nodeSelector: 
      kubernetes.io/arch: amd64
    tolerations: []
    priorityClassName: system-cluster-critical
  pipeline:
    default-timeout-minutes: 60
    default-service-account: default
    default-managed-by-label-value: tekton-pipelines
    disable-affinity-assistant: true
    disable-creds-init: false
    enable-api-fields: stable
    enable-custom-tasks: false
    enable-tekton-oci-bundles: false
    metrics.pipelinerun.duration-type: histogram
    metrics.pipelinerun.level: pipelinerun
    metrics.taskrun.duration-type: histogram
    metrics.taskrun.level: taskrun
    require-git-ssh-secret-known-hosts: false
    running-in-environment-with-injected-sidecars: true
  pruner:
    resources: []
    keep-since: 10080
    schedule: "*/15 * * * *"
  hub:
    params:
      - name: enable-devconsole-integration
        value: "true"
  dashboard:
    readonly: true
```

## What's the problem?

A pipeline is triggered out of a github webhook (i.e. github listener). The pipeline finishes as expected. Instead of staying on the cluster for 7 days, it gets cleared after a while (don't have the exact retention time, but it's not even close to the value I set in `TektonConfig`). 

I set `tekton-resource-pruner` being executed every 15 minutes, which suggests that my patch for `schedule` worked. Looking at the logs, I see it should have kept the pods I am looking for:

```
> k logs tekton-resource-pruner-79qs2-28223775-7nf2q -n tekton-pipelines

... snip ...

$ tkn pipelinerun delete --keep-since=10080 --namespace=tekton-pr --force
0 expired PipelineRuns(Completed) has been deleted in namespace "tekton-pr", kept 13

$ tkn pipelinerun delete --keep-since=10080 --namespace=tekton-release --force
0 expired PipelineRuns(Completed) has been deleted in namespace "tekton-release", kept 2

... snip ...
```

Disabling the pruner altogether fixes the issue. 

Could there be a bug in the pruner job?

Thank you

**Comment by jkandasa** [comment]
@cmorinupgrade `pruner` uses only `tkn` command to remove the expired jobs. That too on the pod `tekton-resource-pruner-*`.
I see your schedules are executed as expected and also the configuration applied to `tkn` as you mentioned, So my guess we may not have issue with pruner. also `tkn` clearly says it deletes 0 items.

at this time no clue, where it went wrong :thinking: 

Can you please disable the pruner job and perform the followings,
* wait till you get enough pipeline runs
* list all the `pipelineruns` on your namespace
* execute `tkn pipelinerun delete --keep-since=10080 --namespace=<your-namespace> --force`
* again list `pipelineruns` on your namespace

can you please also check how many cronjobs configured to pruner? In your case it should be only one. And in that list the container args.
```
$ kubectl get cronjobs --namespace tekton-pipelines
```

**Comment by cmorinupgrade** [comment]
Here's the output:

```
➜ kubectl get cronjobs --namespace tekton-pipelines
NAME                           SCHEDULE       SUSPEND   ACTIVE   LAST SCHEDULE   AGE
tekton-resource-pruner-79qs2   */15 * * * *   False     0        13m             44h
```

I can see the two namespaces in the container arguments, along with all other unrelated namespaces. Is there a global way to just look for specific namespaces in the pruner config? From [this doc](https://tekton.dev/docs/operator/tektonconfig/#pruner-namespace-annotations), it seems like there's a way to skip namespaces. Let's say I got 20 namespaces in my cluster, and only 2 of them should be in scope for the pruner job. Does that mean I need to add the `operator.tekton.dev/prune.skip` annotation on all 18 unrelated namespaces? In an ideal world, I'd rather declare the namespaces I want the pruner to prune, not the other way around.

Thanks!

**Comment by jkandasa** [comment]
@cmorinupgrade there is an option to disable the global pruner job. In the tektonConfig CR, you have to set the pruner `schedule` to empty, the global pruner job will be disabled. However namespace specific jobs will be executed, if the `operator.tekton.dev/prune.schedule` annotation present on a namespace.
So you can set `operator.tekton.dev/prune.schedule` annotation on the required namespaces.

TektonConfig CR:
```yaml
pruner:
  disabled: false
  resources: ["pipelinerun"]
  keep-since: 10080
  schedule: 
```

Namespace:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    operator.tekton.dev/prune.schedule: "*/15 * * * *"
  name: tekton-pr
```
