### ISSUE TITLE
Extend TektonConfig with spec.config.affinity inputs

### ISSUE THREAD

**Issue by jsteenb2** [tektoncd/operator#1824]
### Feature request

We're actively deploying into restricted egress subnets. One thing we have to do now is update the tekton controller deployment resources with the affinity updates. What we want to do is add it into the tekton config alongside our tolerations. This would keep it concise, and remove a lot of burden of having to download and change the release.yaml resources. Looking at affinity assistant, and it doesn't look like it'll solve our needs. The following is our desired output:

```yaml
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  targetNamespace: tekton-pipelines
  profile: all
  config:
    affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: NotIn
                    values:
                      - windows
                  - key: node-role.kubernetes.io/restricted-egress
                    operator: In
                    values:
                      - ''
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/restricted-egress
        operator: Exists
    priorityClassName: system-cluster-critical
```

### Use case

We're usign tekton for a build pipeline, and we need to run that pipeline in a restricted egress subnet. Atm, it requires a lot of updates to the raw yaml releases, which is burdensome and error prone.

**Comment by jkandasa** [comment]
Hi @jsteenb2 thanks to reach us. from `v0.68.0` we have add new field called `options`, with options you can achieve this. https://tekton.dev/docs/operator/tektonconfig/#additional-fields-as-options

```yaml
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  pipeline:
    options:
      deployments:
        tekton-pipelines-controller:
          spec:
            template:
              spec:
                affinity:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                        - matchExpressions:
                          - key: kubernetes.io/os
                            operator: NotIn
                            values:
                              - windows
                          - key: node-role.kubernetes.io/restricted-egress
                            operator: In
                            values:
                              - ''
                nodeSelector:
                tolerations:
                  - effect: NoSchedule
                    key: node-role.kubernetes.io/restricted-egress
                    operator: Exists
                topologySpreadConstraints:
```
However the `priorityClassName` in the options. I will include that. thanks!
