### ISSUE TITLE
ignore struct data type in "AddConfigMapValues" transformer

### ISSUE THREAD

**Issue by jkandasa** [tektoncd/operator#1847]
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: feature-flags
  namespace: openshift-pipelines
data:
  running-in-environment-with-injected-sidecars: 'true'
  results-from: termination-message
  await-sidecar-readiness: 'true'
  coschedule: workspaces
  enforce-nonfalsifiablity: none
  require-git-ssh-secret-known-hosts: 'false'
  set-security-context: 'false'
  enable-tekton-oci-bundles: 'false'
  performance: <v1alpha1.PipelinePerformanceProperties Value>
  send-cloudevents-for-runs: 'false'
  trusted-resources-verification-no-match-policy: ignore
  enable-api-fields: beta
  enable-provenance-in-status: 'true'
  enable-custom-tasks: 'true'
  disable-creds-init: 'false'
  disable-affinity-assistant: 'true'
```
NOTE: `  performance: <v1alpha1.PipelinePerformanceProperties Value>`
* https://github.com/tektoncd/operator/blob/e5c4b7e97662da019ebbacf8e2c42a100882fbc6/pkg/reconciler/kubernetes/tektonpipeline/transform.go#L65
 * https://github.com/tektoncd/operator/blob/e5c4b7e97662da019ebbacf8e2c42a100882fbc6/pkg/reconciler/common/transformers.go#L528
* https://github.com/tektoncd/operator/blob/e5c4b7e97662da019ebbacf8e2c42a100882fbc6/pkg/apis/operator/v1alpha1/tektonpipeline_types.go#L116

`PipelinePerformanceProperties` is a struct and it is added as `string` by https://github.com/tektoncd/operator/blob/e5c4b7e97662da019ebbacf8e2c42a100882fbc6/pkg/reconciler/common/transformers.go#L572

Fix: add only valid fields in to the configMap. ignore struct, map, etc.,
