### ISSUE TITLE
Extend custom annotations support in TektonConfig

### ISSUE THREAD

**Issue by MalekDamian** [tektoncd/operator#1903]
Currently, in documentation for operator v0.68.x is described posibility of using 'options' field in TektonConfig. In my case I would like to annotate the pods. Filebeat is being introduced into the company's standards, and its configuration is based on specific annotations on the pods (e.g. co.elastic.logs/enabled). Those annotations enable Filebeat to forward logs from pods to ELK stack.

The documentation includes a list of fields that are supported, but I can't add annotations in path deployments.*.spec.template.annotations.

Part of TektonConfig:
```yaml
options:
  disabled: false
  deployments:
    tekton-pipelines-controller:
      metadata:
        annotations:
          co.elastic.logs/enabled: 'true'
      spec:
        template:
          metadata:
            annotations:
              co.elastic.logs/enabled: 'true'
```

Based on the configuration above, adding an additional annotation to tekton-pipelines-controller deployment object works fine, but I also need support to add annotations to pod template.
