### ISSUE TITLE
helmchart inflator unable to pull helm chart

### ISSUE THREAD

**Issue by wibed** [tektoncd/operator#1925]
atm i have to manually git pull and mv the chart directory in place because kustomization helmChart inflator
cannot understand the `git+https://` -url.

heres a reproduction:
- command
```shell
kustomize build --enable-helm --load-restrictor=LoadRestrictionsNone . | kubectl apply -f -
```

- file
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../../base/tekton-operator

helmCharts:
  - name: tekton-operator
    releaseName: cluster0
    includeCRDs: true
    valuesInline:

    repo: "git+https://github.com/tektoncd/operator@charts?ref=main"
```
