### ISSUE TITLE
Intendation error at operator deployment

### ISSUE THREAD

**Issue by sheveg** [tektoncd/operator#1938]
# Expected Behavior

Operator deployment is rendered correctly

# Actual Behavior

Operator [deployment] (https://github.com/tektoncd/operator/blob/main/charts/tekton-operator/templates/deployment.yaml) is not rendered due to intendation error at `184`:

```yaml
             - name: WEBHOOK_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
 ```

# Steps to Reproduce the Problem

1. Checkout the repo
2. Render the templates via `helm template`
