### ISSUE TITLE
[e2e] Tektonhubexternaldatabase testcase failing with namespace not found on PPC64LE

### ISSUE THREAD

**Issue by sanskruti1098** [tektoncd/operator#2095]
# Expected Behavior

Testcases should pass.

# Actual Behavior

Failed with namespace not found. [https://dashboard.dogfooding.tekton.dev/#/namespaces/bastion-p/pipelineruns/tekton-operator-ppc64le-nightly-run-pl7xb?pipelineTask=e2e-test-operator&step=run-e2e-tests&view=details](https://dashboard.dogfooding.tekton.dev/#/namespaces/bastion-p/pipelineruns/tekton-operator-ppc64le-nightly-run-pl7xb?pipelineTask=e2e-test-operator&step=run-e2e-tests&view=details)

# Steps to Reproduce the Problem

1. install kubeadm cluster
2. clone operator code
3. run ./test/e2e-test.sh

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  [root@k8s-5d8e5b-bastion-1 operator]# kubectl version -o yaml
  clientVersion:
  buildDate: "2024-03-15T00:08:19Z"
  compiler: gc
  gitCommit: 6813625b7cd706db5bc7388921be03071e1a492d
  gitTreeState: clean
  gitVersion: v1.29.3
  goVersion: go1.21.8
  major: "1"
  minor: "29"
  platform: linux/ppc64le
  kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
  serverVersion:
  buildDate: "2024-01-17T15:41:12Z"
  compiler: gc
  gitCommit: bc401b91f2782410b3fb3f9acf43a995c4de90d2
  gitTreeState: clean
  gitVersion: v1.29.1
  goVersion: go1.21.6
  major: "1"
  minor: "29"
  platform: linux/ppc64le
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

Failure log:

=== RUN   TestTektonChainDeployment
    03_tektonchaindeployment_test.go:45: Tekton chain is not available for "linux/ppc64le"
--- SKIP: TestTektonChainDeployment (0.00s)
=== RUN   TestTektonChainTutorialTestSuite
    04_tektonchainsgettingstartedtutorial_test.go:61: Tekton chain is not available for "linux/ppc64le"
--- SKIP: TestTektonChainTutorialTestSuite (0.00s)
=== RUN   TestTektonHubTestSuite
=== RUN   TestTektonHubTestSuite/Test01_DeployDefault
2024-03-12T12:43:23.219Z        debug   common/05_tektonhubdeployment_test.go:110       removing the tekton hub cr if any
2024-03-12T12:43:23.239Z        debug   common/05_tektonhubdeployment_test.go:115       test environment ready. starting the actual test
=== RUN   TestTektonHubTestSuite/Test02_DeployWithExternalDatabase
2024-03-12T12:44:33.281Z        debug   common/05_tektonhubdeployment_test.go:110       removing the tekton hub cr if any
2024-03-12T12:44:38.333Z        debug   common/05_tektonhubdeployment_test.go:115       test environment ready. starting the actual test
2024-03-12T12:44:38.427Z        debug   common/05_tektonhubdeployment_test.go:325       wait for external database deployment becomes ready     {"namespace": "hub-external-db", "deploymentName": "tekton-hub-db"}
2024-03-12T12:45:13.447Z        debug   common/05_tektonhubdeployment_test.go:331       external database deployment is ready
    05_tektonhubdeployment_test.go:350: 
                Error Trace:    /root/tekton/operator/test/e2e/common/05_tektonhubdeployment_test.go:350
                                                        /root/tekton/operator/test/e2e/common/05_tektonhubdeployment_test.go:144                Error:          Received unexpected error:
                                namespaces "tekton-pipelines" not found
                Test:           TestTektonHubTestSuite/Test02_DeployWithExternalDatabase
2024-03-12T12:45:13.510Z        info    common/05_tektonhubdeployment_test.go:123       test failed, executing debug commands  {"testName": "TestTektonHubTestSuite/Test02_DeployWithExternalDatabase"}

------------------- debug information -------------------
$ kubectl get tektonconfig
