### ISSUE TITLE
helm chart 0.71.0 missing some crd (ManualApprovalGate)

### ISSUE THREAD

**Issue by alekc** [tektoncd/operator#2207]
# Expected Behavior
being able to deploy

# Actual Behavior
Tekton operator fails to watch `manualapprovalgates` 

# Steps to Reproduce the Problem

Install helm chart
```
  repo_url        = "https://github.com/tektoncd/operator.git"
  path            = "charts/tekton-operator"
  target_revision = "v0.71.0"
```

with following config 
```
installCRDs: true
openshift:
  openshift: false
operator:
  logLevel: info
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
pruner:
  image:
    tag: latest
service:
  createServiceMonitor: false
## Annotations to be added to all pods deployed by this chart.
podAnnotations: {}
## Settings for controlling the placement of all pods deployed by this chart.
## see https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
nodeSelector: {}
tolerations: []
affinity: {}
```

pod will report several errors
```
W0612 15:08:41.378103       1 reflector.go:535] k8s.io/client-go@v1.5.2/tools/cache/reflector.go:229: failed to list *v1alpha1.ManualApprovalGate: the server could not find the requested resource (get manualapprovalgates.operator.tekton.dev)
```

by the look of it, the CRD for the ManualApprovalGate has not been included in the helm chart
