### ISSUE TITLE
ImagePullBackOff for pruner

### ISSUE THREAD

**Issue by tomalexander** [tektoncd/operator#2368]
# Expected Behavior

The tekton pruner should run successfully

# Actual Behavior

```
  containerStatuses:
  - image: gcr.io/tekton-releases/dogfooding/tkn:8d4383ff675cdf42b0006fca9b5b3b0c1d6180ff0013805242c877352e03a359
    imageID: ""
    lastState: {}
    name: tkn-pruner
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "gcr.io/tekton-releases/dogfooding/tkn:8d4383ff675cdf42b0006fca9b5b3b0c1d6180ff0013805242c877352e03a359"
        reason: ImagePullBackOff
```

# Steps to Reproduce the Problem

1. I installed `tekton-operator-0.73.0`
2. Enabled the pruner with:
```
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  profile: all
  targetNamespace: tekton-pipelines
  pruner:
    resources:
      - pipelinerun
      - taskrun
    keep: ~
    keep-since: 86400
    schedule: "0,30 * * * *"
```

3. The pruner fails to start.

But you can easily see this issue without installing tekton. First you can see the references to this specific container in the code base: https://github.com/search?q=org%3Atektoncd+8d4383ff675cdf42b0006fca9b5b3b0c1d6180ff0013805242c877352e03a359&type=code

And then you can try pulling said image:
```
$ docker pull 'gcr.io/tekton-releases/dogfooding/tkn:8d4383ff675cdf42b0006fca9b5b3b0c1d6180ff0013805242c877352e03a359'
Error response from daemon: manifest for gcr.io/tekton-releases/dogfooding/tkn:8d4383ff675cdf42b0006fca9b5b3b0c1d6180ff0013805242c877352e03a359 not found: manifest unknown: Failed to fetch "8d4383ff675cdf42b0006fca9b5b3b0c1d6180ff0013805242c877352e03a359" from request "/v2/tekton-releases/dogfooding/tkn/manifests/8d4383ff675cdf42b0006fca9b5b3b0c1d6180ff0013805242c877352e03a359".
```

# Additional Info

- Kubernetes version:

```
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.30.2
```

- Tekton Pipeline version:

```
v0.62.3
```
