### ISSUE TITLE
Add feature-flag "enable-kubernetes-sidecar"

### ISSUE THREAD

**Issue by say5** [tektoncd/operator#2467]
### Feature request

Add feature-flag `enable-kubernetes-sidecar` to operator.

### Use case

Tekton pipelines controller [supports flag](https://tekton.dev/vault/pipelines-main/additional-configs/#customizing-the-pipelines-controller-behavior) `enable-kubernetes-sidecar` would be great to be able to control it using operator.

**Comment by PuneetPunamiya** [comment]
Yep thanks for reporting the issue and apologies for late reply, as of today we can still add it through options

```yaml
options:
      configMaps:
        feature-flags:
          data:
            enable-kubernetes-sidecar: "true"
```
