### ISSUE TITLE
Operator v0.75.0 deploys broken TektonResults database "cannot create directory ‘/bitnami/postgresql/data’: Permission denied"

### ISSUE THREAD

**Issue by Sir-Jacques** [tektoncd/operator#2671]
# Expected Behavior
Upgrading from v0.74.0 to v0.75.0 should work when using default configuration.

# Actual Behavior
A new feature "TektonResult" is automatically deployed by the v0.75.0 operator. It tries to deploy a postgres db, which does not become healthy due to filesystem permissions. The postgres pod logs this:
```
postgresql 09:11:36.57                                                                                                                                                                                      
postgresql 09:11:36.58 Welcome to the Bitnami postgresql container                                                                                                                                          
postgresql 09:11:36.58 Subscribe to project updates by watching https://github.com/bitnami/containers                                                                                                       
postgresql 09:11:36.58 Submit issues and feature requests at https://github.com/bitnami/containers/issues                                                                                                   
postgresql 09:11:36.58                                                                                                                                                                                      
postgresql 09:11:36.59 INFO  ==> ** Starting PostgreSQL setup **                                                                                                                                            
postgresql 09:11:36.61 INFO  ==> Validating settings in POSTGRESQL_* env vars..                                                                                                                             
postgresql 09:11:36.61 INFO  ==> Loading custom pre-init scripts...                                                                                                                                         
postgresql 09:11:36.62 INFO  ==> Initializing PostgreSQL database...                                                                                                                                        
mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied
```

# Steps to Reproduce the Problem
1. Deploy v0.75.0 helm chart using the values.yaml below (using AWS EKS v1.31.6-eks-bc803b4)

# Additional Info
Kubernetes version: **Kubernetes: Server Version: version.Info{Major:"1", Minor:"31", GitVersion:"v1.31.6-eks-bc803b4", GitCommit:"7555883c9fd5b1ff4a68ad9feb15f9727bfa4b4a", GitTreeState:"clean", BuildDate:"2025-02-17T20:40:26Z", GoVersion:"go1.22.12", Compiler:"gc", Platform:"linux/amd64"}**
Tekton operator version: **v0.75.0**
Tekton pipeline version: **v0.68.0**

helm values.yaml:
```
installCRDs: true
tolerations:
  - key: node.kubernetes.io/infra
    operator: Exists
nodeSelector:
  type: infra
```

PV storageclass:
```
allowVolumeExpansion: true
allowedTopologies:
- matchLabelExpressions:
  - key: topology.ebs.csi.aws.com/zone
    values:
    - eu-west-1a
    - eu-west-1b
    - eu-west-1c
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: gp3
parameters:
  csi.storage.k8s.io/fstype: xfs
  encrypted: "true"
  type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

```
