### ISSUE TITLE
Missing CRDs if installCRDs: true and also missing crds when component==false

### ISSUE THREAD

**Issue by Syntax3rror404** [tektoncd/operator#2773]
# Expected Behavior
Tekton operator installs all component which are defined in the TektonConfig
# Actual Behavior
`"Unhandled Error" err="k8s.io/client-go@v1.5.2/tools/cache/reflector.go:251: Failed to watch *v1alpha1.TektonPruner: failed to list *v1alpha1.TektonPruner: the server could not find the requested resource (get tektonpruners.operator.tekton.dev)" logger="UnhandledError"`

# Steps to Reproduce the Problem

1. Use clean cluster or remove all tekton CRDs
2. Install tekton operator with value `installCRDs: true`
3. Install tekton compoents by applying the following TektonConfig

```yaml
# TektonConfig
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
  namespace: tekton-operator
spec:
  targetNamespace: tekton-pipelines
  targetNamespaceMetadata:
    labels: {}
    annotations: {}

  profile: all

  pruner:
    disabled: true
  chain:
    disabled: true
  result:
    disabled: true
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: v1.32.3
  Kustomize Version: v5.5.0
  Server Version: v1.32.5
  ```

- Tekton Pipeline version:

N/A (because no installation possible because of the error posted above)
