### ISSUE TITLE
Components customization

### ISSUE THREAD

**Issue by pvlltvk** [tektoncd/operator#311]
Hi, everyone!

Is there any possibility to set/customize some parameters of Tekton components which are installed by Operator? 
For example, I want to set some feature-flags as described [here](https://github.com/tektoncd/pipeline/blob/main/docs/install.md#customizing-the-pipelines-controller-behavior)

**Comment by nikhil-thomas** [comment]
At present, we don't expose any of the parameter through our Operator's CRDs.

However, potential workaround is to edit them in the config map of respective components. There is a gotcha though, operator might reset custom changes in successive reconciles.

The issue https://github.com/tektoncd/operator/issues/149 needs to be resolved for the above workaround to work reliably.

Customization options are something we are planning. However, the UX is not defined yet (change it in CR spec or add a new ConfigMap etc).

@pvlltvk how would you prefer to set those customizations if you can pick any ux.

**Comment by pvlltvk** [comment]
Hi @nikhil-thomas!

I would definitely prefer to set it in CR spec.

**Comment by nikhil-thomas** [comment]
How about an updated spec like:
```
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
Metadata:
name: config
Spec:
  Profile: all
  targetNamespace: tekton-pipelines
  pipelineConfig:
    prunePTRuns: 
    frequency: int # will take the frequency of pruning
    ptRunsToKeep: int # will take max runs to keep
    ptAge: int  # max age allowed of runs
    relatedResource: bool # want to prune related res
    default-param1: #items from https://github.com/tektoncd/pipeline/blob/main/config/config-defaults.yaml
    default-param2:
    ...
    feature-flag1: #items from https://github.com/tektoncd/pipeline/blob/main/config/config-feature-flags.yaml
    feature-flag2:
    ...
  triggersConfig: {}
  dasboardConfig:
    param1:
    param2:
  ```

@pvlltvk 
cc @houshengbo @vincent-pli @vdemeester @savitaashture @pradeepitm12 @sm43
