### ISSUE TITLE
TektonConfig object gets created without any default values

### ISSUE THREAD

**Issue by sm43** [tektoncd/operator#368]
Sometimes, webhook takes time to start and if the controller is started before it
it will create a `TektonConfig` object
but as webhook is not started the object will not have any default values.

```
  apiVersion: operator.tekton.dev/v1alpha1
  kind: TektonConfig
  metadata:
    name: config
  spec:
    addon: {}
    pipeline: {}
    profile: all
    pruner: {}
    targetNamespace: tekton-pipelines

```
