### ISSUE TITLE
Result component was not installed when set the installation profile as all

### ISSUE THREAD

**Issue by wzhanw** [tektoncd/operator#407]
### Feature request
The Tekton result component was not installed when set the installation profile as all. 
is this by design？

I see the results installation requires some prerequisites.  I segguest we can document in this readme and let user finish them before the installation if he wants all the components.

### Use case
Installed the Tekton with below installConfig,  assume all components should be installed as I selected `all`.
```
spec:
  addon: {}
  config: {}
  pipeline:
    disable-creds-init: false
    disable-home-env-overwrite: true
    disable-working-directory-overwrite: true
    enable-api-fields: stable
    enable-custom-tasks: false
    enable-tekton-oci-bundles: false
    require-git-ssh-secret-known-hosts: false
    running-in-environment-with-injected-sidecars: true
    scope-when-expressions-to-task: false
  profile: all
  pruner: {}
  targetNamespace: tekton-pipelines
  trigger: {}
```
