### ISSUE TITLE
Ability to set priorityClassName in TektonConfig for resources created by the operator 

### ISSUE THREAD

**Issue by tonygilkerson** [tektoncd/operator#580]
### Feature request

I would like to set the priorityClassName of resources created by the Tekton-Operator, i.e. tekton-dashboard and tekton-pipelines-controller deployments.  It would be nice to enable this in the TektonConfig as shown below in the yaml snipit.

```yaml
kind: TektonConfig
metadata:
  name: config
spec:
  ...
  dashboard:
    priorityClassName: foo
    ...
  pipeline:
    priorityClassName: foo
    ...
  targetNamespace: tekton-pipelines
  trigger:
    priorityClassName: foo
```

### Use case

We need a way to protect core services even when the cluster is over allocated we do this with priority classes.  Also, on our cluster we have several research teams that often want to deploy very large long-running jobs.  We have a method of allowing teams with "credits" to "buy" resources on the system.  The way that we enforce this is by using priorityClasses and let the kubernetes scheduler do it job.   You can think of it as AWS spot instances.  We have a spot priorityClass that can run as long as the system has free resources, but can get preempted if resources are low.  

Therefore if team-a and team-b each have pipelines running in their respective namespaces then I need a way to distinguish the two using priorityClasses
