### ISSUE TITLE
Operator nightly build failed

### ISSUE THREAD

**Issue by dibyom** [tektoncd/operator#584]
# Expected Behavior
Nightly build passes

# Actual Behavior
Nightly failed with a `CreateContainerConfigError`

URL: https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-nightly/pipelineruns/operator-release-nightly-hhtvk?pipelineTask=publish-images-platform-openshift&step=container-registy-auth&view=status

Step failure:
```yaml
container: step-container-registy-auth
name: container-registy-auth
waiting:
  message: failed to create subPath directory for volumeMount "ws-nhdf5" of container "step-container-registy-auth"
  reason: CreateContainerConfigError
```

Pod Status:

```yaml
status:
  phase: Failed
  message: Pod was active on the node longer than the specified deadline
  reason: DeadlineExceeded
  podIP: 10.56.1.104
  podIPs:
    - ip: 10.56.1.104
  startTime: '2022-01-20T04:08:17Z'
  initContainerStatuses:
    - name: place-tools
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2022-01-20T04:08:21Z'
          finishedAt: '2022-01-20T04:08:21Z'
          containerID: 'docker://3e5a8fed8195e542b7652b921c7775a077ce335a36fdad1dbb85a54ca6d29715'
      lastState: {}
      ready: false
      restartCount: 0
      image: 'sha256:48c7a85c10d9c90fff936190023fb4fc6892d0cdf1671c2347135cef4d2713a0'
      imageID: 'docker-pullable://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint@sha256:34ee7658bb8a657584e1ada8e84121758cc5d067c1f0740873d614d07423886f'
      containerID: 'docker://3e5a8fed8195e542b7652b921c7775a077ce335a36fdad1dbb85a54ca6d29715'
    - name: place-scripts
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2022-01-20T04:08:22Z'
          finishedAt: '2022-01-20T04:08:22Z'
          containerID: 'docker://e99ba817450f08908ae2db1ae6b2caa913cf0ef2a5fa8620f81913acc82bd497'
      lastState: {}
      ready: false
      restartCount: 0
      image: 'sha256:004c7e180f32e8868c51c81388cf2930999146ea681d3f80d767edcf781b3614'
      imageID: 'docker-pullable://gcr.io/distroless/base@sha256:cfdc553400d41b47fd231b028403469811fcdbc0e69d66ea8030c5a0b5fbac2b'
      containerID: 'docker://e99ba817450f08908ae2db1ae6b2caa913cf0ef2a5fa8620f81913acc82bd497'
  containerStatuses:
    - name: step-container-registy-auth
      state:
        running:
          startedAt: '2022-01-20T04:08:26Z'
      lastState: {}
      ready: false
      restartCount: 0
      image: 'gcr.io/go-containerregistry/crane:debug'
      imageID: 'docker-pullable://gcr.io/go-containerregistry/crane@sha256:45b43b758d6570b93ce918ff8b793720b7fc758e3b696d85ba8a5a98e6ba6482'
      containerID: 'docker://98aa4723c25baa6239f1c33c3a3cd50b6a05581ec7c3fb93c9d6883e09d80248'
    - name: step-koparse
      state:
        running:
          startedAt: '2022-01-20T04:08:25Z'
      lastState: {}
      ready: false
      restartCount: 0
      image: 'gcr.io/tekton-releases/dogfooding/koparse:latest'
      imageID: 'docker-pullable://gcr.io/tekton-releases/dogfooding/koparse@sha256:5945f709f5533347e2fac2f7e757a2acde2ce25418a7193489bf49027aa0497f'
      containerID: 'docker://0410162ca0485ad153c7deb6ee11ef40a9a112a5987e854277690d024098fc74'
    - name: step-run-kustomize-ko
      state:
        running:
          startedAt: '2022-01-20T04:08:24Z'
      lastState: {}
      ready: false
      restartCount: 0
      image: 'gcr.io/tekton-releases/dogfooding/ko-gcloud:latest'
      imageID: 'docker-pullable://gcr.io/tekton-releases/dogfooding/ko-gcloud@sha256:ef803ef52ed2bbcc058a42ecfba8207aac99b95f5231de68a59b5260161e4a0a'
      containerID: 'docker://5e4461190daa75d3111620e0f946544d57a7b4b5ae8a3c5653eb6e8a2da877f3'
    - name: step-tag-images
      state:
        running:
          startedAt: '2022-01-20T04:08:25Z'
      lastState: {}
      ready: false
      restartCount: 0
      image: 'gcr.io/go-containerregistry/crane:debug'
      imageID: 'docker-pullable://gcr.io/go-containerregistry/crane@sha256:45b43b758d6570b93ce918ff8b793720b7fc758e3b696d85ba8a5a98e6ba6482'
      containerID: 'docker://5f4db4d1faacab9209c995cee219c053eb2386fe99301a1b2ce11626bc4c8cea'
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
