### ISSUE TITLE
Consistent API for Tekton configurations 

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/operator#759]
### Feature request

The `TektonConfig` CR provides a convenient UX for configuring the behaviour of various Tetkon components on the cluster however the UX is inconsistent across various attributes:

```
    running-in-environment-with-injected-sidecars: true
    metrics.taskrun.duration-type: histogram
    metrics.pipelinerun.duration-type: histogram
    params:
      - name: enableMetrics
        value: 'true'
      - name: createRbacResource
        value: 'false'
```

Specifying some config values as params makes it error-prone and undiscoverable by the user in contrast to the rest of config attributes that are strongly typed and are directly on the CR. 

The above config for example could have been specified as the following with respect to consistency and distinguishing platfrom-specific attributes:

```
    running-in-environment-with-injected-sidecars: true
    metrics.taskrun.duration-type: histogram
    metrics.pipelinerun.duration-type: histogram
    openshift:
      enable-metrics: true
```
