### ISSUE TITLE
Webhook timeout when editing the TektonConfig

### ISSUE THREAD

**Issue by v1nc3nt27** [tektoncd/operator#835]
Editing the TektonConfig after installing the chart throws `│ Error: config failed to run apply: error when creating "/tmp/896304782kubectl_manifest.yaml": Internal error occurred: failed calling webhook "webhook.operator.tekton.dev": failed to call webhook: Post "https://tekton-operator-webhook.tekton-operator.svc:443/defaulting?timeout=10s": context deadline exceeded` and I cannot figure out what the underlying issue is. 

I clone the repo and then install the chart via terraform:

```
resource "helm_release" "tekton-cd-operator" {
  name             = "tekton-operator"
  chart            = "${local.operator_git_path}/chart"
  version          = "0.59.0"
  namespace        = "tekton-operator"
  create_namespace = true
  cleanup_on_fail  = true

    set {
    name  = "installCRDs"
    value = "true"
  }
]
}
```

Afterwards, I'm trying to adapt the config:

```
resource "kubectl_manifest" "tekton-cd-operator-config" {
  yaml_body = <<YAML
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  profile: all
  targetNamespace: "tekton-pipelines"
  pruner:
    resources:
    - pipelinerun
    - taskrun
    keep: 100
    schedule: "0 8 * * *"
  config:
    nodeSelector:
      gpu: unavailable
YAML
}
```

I'm using the latest version 0.59.0, but I have also tested with 0.57.0 with the same result. I have also tested an approach where I set `installCRDs` to `false` and installed the CRDs via kubectl but same error.

The webhook is definitely running and I can already access it via the service. I'm out of ideas here. I'm grateful for any help. Thanks!
